---

services:
  - name: docker:dind
    command: [ "dockerd", "--host=tcp://localhost:2375", "--mtu=1450" ]
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/

build:
  stage: build
  image: docker:stable
  before_script:
    - docker login --username "${REGISTRY_USER}" --password "${REGISTRY_PASSWORD}" "${REGISTRY_URL}"
  script:
    - docker build --pull --tag "${REGISTRY_URL}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}" .
    - docker push "${REGISTRY_URL}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"
